on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PASSPHRASE }}" | SSH_ASKPASS=/bin/echo ssh-add ~/.ssh/private_key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/private_key \
              ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            eval $(ssh-agent -s)
            echo "${{ secrets.SSH_PASSPHRASE }}" | SSH_ASKPASS=/bin/echo ssh-add ~/.ssh/id_rsa
            git pull origin main
          EOF
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
