on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          # Guardar la clave privada en ~/.ssh/private_key
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key

          # Iniciar el agente SSH
          eval $(ssh-agent -s)

          # Agregar la clave privada al agente SSH (sin passphrase)
          ssh-add ~/.ssh/private_key


      - name: Deploy to EC2
        run: |
          # Conectar a EC2 y realizar el pull del repositorio
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/private_key \
              ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/paleta_de_colores
            git pull origin main
            screen -S flask_app -X quit
            screen -dmS flask_app sudo flask run --host=0.0.0.0 --port=80
          EOF
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

