on:
  push:
    branches:
      - main  # Solo se activa cuando hay un push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2 (Despliegue en EC2)
        run: |
          ssh -i "${{ secrets.EC2_SSH_KEY }}" -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/paleta_de_colores  # Ruta del proyecto en el servidor EC2
            git pull origin main  # Trae los últimos cambios
          EOF
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
